FROM node as react-build
WORKDIR /app
# copy package.json to app directory, dot represents current directory which is the app directory
COPY package.json .
RUN npm install
# copy all files from current directory to app directory
COPY . .
ARG REACT_APP_NAME
ENV REACT_APP_NAME=${REACT_APP_NAME}
# CMD is the command that will be run when the container is started
RUN npm run build

FROM nginx
COPY --from=react-build /app/build /usr/share/nginx/html