FROM node
WORKDIR /app
# copy package.json to app directory, dot represents current directory which is the app directory
COPY package.json .
RUN npm install
# copy all files from current directory to app directory
COPY . .
ENV REACT_APP_NAME=myName
EXPOSE 3000
# CMD is the command that will be run when the container is started
CMD ["npm", "start"]